spring.application.name=quoteEveryDay

spring.profiles.active=local

# application.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_FROM}
spring.mail.password=${MAIL_PASSWORD}
mail.to=${MAIL_TO}
